root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/agent ./cmd/agent"
  bin = "./tmp/agent"
  include_ext = ["go", "yaml"]
  exclude_dir = ["tmp", "vendor", "data"]
  delay = 1000

[build.env]
  AGENT_CONFIG_DIR = "./config"
  AGENT_ENV = "dev"

[log]
  time = false

[misc]
  clean_on_exit = true
